module.exports = { ns_obj: {'sru-zr':'http://www.loc.gov/zing/srw/',
		'escidocItem':'http://www.escidoc.de/schemas/item/0.10',
		'escidocMetadataRecords':'http://www.escidoc.de/schemas/metadatarecords/0.5',
		'escidocContainer':'http://wwww.escidoc.de/schemas/container/0.4',
		'escidocContentStreams':'http://www.escidoc.de/schemas/contentstreams/0.7',
		'escidocComponents':'http://www.escidoc.de/schemas/components/0.9',
		'version':'http://escidoc.de/core/01/properties/version/',
		'release':'http://escidoc.de/core/01/properties/release/',
		'prop':'http://escidoc.de/core/01/properties/',
		'srel':'http://escidoc.de/core/01/structural-relations/',
		'xlink':'http://www.w3.org/1999/xlink',
		't':'http://www.tei-c.org/ns/1.0' },
		debug: new Boolean(true),
		xslt_params: [],
		xslt_removeNamespace: './data/xslt/remove-namespace.xsl',
		xslt_filepath: './data/xslt/dkclarintext2cmdi_v5.xsl',
		//xslt_filepath: './data/xslt/dkclarinanno2cmdi_v2.xsl',
		xsd_filepath: './data/xsd/teiHeader.xsd', //TEI
		clarin_schema_url: 'http://www.clarin.eu/cmd/',
		dkclarin_cmd_profile: 'clarin.eu:cr1:p_1380106710826', //TEI
		dkclarin_cmd_schema_url: 'http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_1380106710826/xsd', //TEI
		xmllint_dir: './data/xmllint',
		log_dir: './output-test',
		pidmanager_host: 'devtools.clarin.dk',
		//pidmanager_host: 'clarin.dk',
		pidmanager_path: '/pidmanager/pid/handle/',
		pidmanager_auth_user: 'clarindk',
		pidmanager_auth_pass: 'password',
		//pidmanager_auth_pass: '94sjef.boss',
		updater_host: 'devtools.clarin.dk',
		updater_port: '80',
		escidoc_host: 'devtools.clarin.dk',
		//escidoc_host: 'core.clarin.dk',
		escidoc_ir_path: '/ir/item/',
		escidoc_handle: 'ESCIDOC-EmqvvBMNAo1394599259105',
		pid_url_host: 'devtools.clarin.dk',
		//pid_url_host: 'clarin.dk',
		pid_url_path: '/handle',
		target_context_model_prop: '//escidocItem:properties/srel:context',
		target_context_model_pub: 'dkclarin:8003',
		target_context_model_aca: 'dkclarin:8001',
		target_mdrecord_name: 'CMD', // CMD (TEI and DATA)
		target_tei_keywords_xpath: '//escidocMetadataRecords:md-record[@name=\"TEI\"]/t:teiHeader/t:profileDesc/t:textClass/t:keywords', // start TEI custom mods post-transform
		target_tei_monogr_title_xpath: '//escidocMetadataRecords:md-record[@name=\"TEI\"]/t:teiHeader/t:fileDesc/t:sourceDesc/t:biblStruct/t:monogr/t:title',
		target_tei_notesStmt_note_attr: '//escidocMetadataRecords:md-record[@name=\"TEI\"]/t:teiHeader/t:fileDesc/t:notesStmt/t:note[@resp]',
		target_tei_idno_uri: '//escidocMetadataRecords:md-record[@name=\"TEI\"]/t:teiHeader/t:fileDesc/t:sourceDesc/t:biblStruct/t:idno[@type=\"url\"]',
		target_cmdi_textClass_xpath: '/CMD/Components/teiHeader/profileDesc/textClass',
		target_cmdi_monogr_title_xpath: '/CMD/Components/teiHeader/fileDesc/sourceDesc/biblStruct/monogr/title',
		target_cmdi_notesStmt_note_attr: '/CMD/Components/teiHeader/fileDesc/notesStmt/note',
		target_cmdi_idno_uri: '/CMD/Components/teiHeader/fileDesc/sourceDesc/biblStruct/idno[@type=\"uri\"]',
		target_cmdi_publStmt: '/CMD/Components/teiHeader/fileDesc/publicationStmt',
 		target_cmdi_biblStruct: '/CMD/Components/teiHeader/fileDesc/sourceDesc/biblStruct', // end TEI custom mods post-transform
		target_tei_anno_appl_xpath: '//escidocMetadataRecords:md-record[@name=\"TEI\"]/t:teiHeader/t:encodingDesc/t:appInfo/t:application', // start TEI anno custom mods
		target_cmdi_encodingDesc_xpath: '/CMD/Components/teiHeader/encodingDesc', // end TEI anno custom mods
		update_comment: '12-03-2014, MS. New CMDI md-record created and assigned PIDs to new version.'
};
